Remove use of alias
The alias combinator was causing ocaml-tree-sitter to fail the following
assertion:

Error: exception File "OSS/libs/ocaml-tree-sitter-core/src/gen/lib/CST_grammar_conv.ml", line 168, characters 8-14: Assertion failed
    Raised at Tree_sitter_gen__CST_grammar_conv.translate.translate in file "OSS/libs/ocaml-tree-sitter-core/src/gen/lib/CST_grammar_conv.ml", line 168, characters 8-34
Called from Tree_sitter_gen__CST_grammar_conv.translate_rules.(fun) in file "OSS/libs/ocaml-tree-sitter-core/src/gen/lib/CST_grammar_conv.ml", line 226, characters 15-40
Called from Stdlib__List.map in file "list.ml", line 87, characters 15-19
Called from Stdlib__List.map in file "list.ml", line 88, characters 14-21
Called from Tree_sitter_gen__CST_grammar_conv.of_tree_sitter in file "OSS/libs/ocaml-tree-sitter-core/src/gen/lib/CST_grammar_conv.ml", line 267, characters 22-45
Called from Dune__exe__Ocaml_tree_sitter_main.gen in file "OSS/libs/ocaml-tree-sitter-core/src/gen/bin/Ocaml_tree_sitter_main.ml", line 60, characters 16-67
Called from Dune__exe__Ocaml_tree_sitter_main.safe_run in file "OSS/libs/ocaml-tree-sitter-core/src/gen/bin/Ocaml_tree_sitter_main.ml", line 37, characters 6-10

    Try --help.